name: Compile Kernel POCO F4 GT

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    steps:
    - name: Ambil Bahan Baku (Source Code)
      uses: actions/checkout@v4

    - name: Siapkan Lingkungan Kerja & Library Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential binfmt-support libssl-dev ccache libelf-dev bison flex

        - name: Unduh Google Clang Compiler Resmi
      run: |
        mkdir -p $GITHUB_WORKSPACE/clang
        cd $GITHUB_WORKSPACE/clang
        # Pastikan URL di bawah ini tertulis utuh dalam satu baris penuh tanpa terpotong
        wget -q https://googlesource.com
        tar -xzf clang-r450784d.tar.gz
        echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH

    - name: Mulai Menggabungkan Konfigurasi dan Memasak
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CC=clang
        
        # 1. Menginisialisasi basis konfigurasi utama GKI Google
        make O=out ARCH=arm64 gki_defconfig
        
        # 2. Menggabungkan bumbu khusus milik POCO F4 GT (vendor ingres)
        cat arch/arm64/configs/vendor/ingres_GKI.config >> out/.config
        
        # 3. Proses memasak utama menggunakan kekuatan prosesor server cloud
        make O=out ARCH=arm64 -j$(nproc)

    - name: Cari dan Ambil Hasil Masakan (Image)
      run: |
        ls -la out/arch/arm64/boot/
        
